<!-- reshape() -->

In [ ]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_array = array.reshape(3,4)
print(new_array)

In [ ]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
display_array(array)

new_array = array.reshape(2,2,3)

display_array(new_array)

In [ ]:
# ACCESS ELEMENTS IN ARRAY
import numpy as np
array = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

for i in array:
    for j in i:
        print(j)
print(array.ndim) 

In [ ]:
# nditer()
array = np.array([[[2,3],[4,5]],[[6,7],[8,9]]])

array_iter = np.nditer(array)
print(array_iter)

print(next(array_iter))


print(next(array_iter))

In [ ]:
# ndenumerate()
arr = np.array([2,3,4,5,6])

for index,value in np.ndenumerate(arr):
    print(index,value)

In [ ]:
# zeroes()
arr = np.zeros((7,7), dtype=int)

arr

In [ ]:
# arrange()

In [ ]:
var = list(range(5,10))
var

[5, 6, 7, 8, 9]

In [1]:
import numpy as np
arr = np.array([2,3,4,5,6])
arr

array([2, 3, 4, 5, 6])

In [ ]:
arr = np.arange(2,7) ## last element is not icluded 
arr

array([2, 3, 4, 5, 6])

In [ ]:
arr = np.arange(2,7,3) ## last element is not icluded 
arr

array([2, 5])

In [ ]:
arr = np.arange(0,20,2) ## last element is not icluded 
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr = np.arange(1,20,2) ## last element is not icluded 
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
arr = np.arange(20,1,-1) ## last element is not icluded 
arr

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2])

In [ ]:
arr = np.arange(-10,5) ## last element is not icluded 
arr

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4])

## linspace()

In [ ]:
linspace() >> return an array evenly spaced values


syntax:
np.linspace(start,end, num = 50)

In [8]:
arr = np.linspace(1,50, num= 50,retstep=True)
arr

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
        40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.]),
 1.0)

In [ ]:
arr = np.linspace(1,10, num= 50 )
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
arr = np.linspace(10,20)
arr

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [6]:
arr = np.linspace(1,1.01 )
arr

array([1.        , 1.00020408, 1.00040816, 1.00061224, 1.00081633,
       1.00102041, 1.00122449, 1.00142857, 1.00163265, 1.00183673,
       1.00204082, 1.0022449 , 1.00244898, 1.00265306, 1.00285714,
       1.00306122, 1.00326531, 1.00346939, 1.00367347, 1.00387755,
       1.00408163, 1.00428571, 1.0044898 , 1.00469388, 1.00489796,
       1.00510204, 1.00530612, 1.0055102 , 1.00571429, 1.00591837,
       1.00612245, 1.00632653, 1.00653061, 1.00673469, 1.00693878,
       1.00714286, 1.00734694, 1.00755102, 1.0077551 , 1.00795918,
       1.00816327, 1.00836735, 1.00857143, 1.00877551, 1.00897959,
       1.00918367, 1.00938776, 1.00959184, 1.00979592, 1.01      ])

In [ ]:
arr = np.linspace(10,20 , num = 5,retstep=True)
arr

(array([10. , 12.5, 15. , 17.5, 20. ]), 2.5)

In [ ]:
arr = np.linspace(100,250 , num = 200,retstep=True)
arr

(array([100.        , 100.75376884, 101.50753769, 102.26130653,
        103.01507538, 103.76884422, 104.52261307, 105.27638191,
        106.03015075, 106.7839196 , 107.53768844, 108.29145729,
        109.04522613, 109.79899497, 110.55276382, 111.30653266,
        112.06030151, 112.81407035, 113.5678392 , 114.32160804,
        115.07537688, 115.82914573, 116.58291457, 117.33668342,
        118.09045226, 118.84422111, 119.59798995, 120.35175879,
        121.10552764, 121.85929648, 122.61306533, 123.36683417,
        124.12060302, 124.87437186, 125.6281407 , 126.38190955,
        127.13567839, 127.88944724, 128.64321608, 129.39698492,
        130.15075377, 130.90452261, 131.65829146, 132.4120603 ,
        133.16582915, 133.91959799, 134.67336683, 135.42713568,
        136.18090452, 136.93467337, 137.68844221, 138.44221106,
        139.1959799 , 139.94974874, 140.70351759, 141.45728643,
        142.21105528, 142.96482412, 143.71859296, 144.47236181,
        145.22613065, 145.9798995 , 146.

## eye ()

In [ ]:
eye() >> return an array with ones on diagonal and zeros elsewhere

syntax: 
    
np.eye(shape,dtype)


In [ ]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr = np.eye(5,dtype=int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [17]:
arr = np.eye(5,4,dtype=int)
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

## identity()

In [ ]:
identity() >> return array with rows = columns >> ones at diagonal & zeros elsewhere

syntax:
np.identity(shape,dtype)

In [ ]:
arr = np.identity(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr = np.identity(5,dtype=int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [9]:
arr = np.identity(5,3,dtype=int)
arr

TypeError: identity() got multiple values for argument 'dtype'

# Random 

In [ ]:
used to generate random values / numbers 

1. rand()
2. randint()
3. randn()

## rand()

In [ ]:
Return a values between 0 to 1 

syntax:
    
np.random.rand(no) ## no of values we are going to get from 0 to 1

In [ ]:
arr = np.random.rand(5)
arr

array([0.5166304 , 0.97703903, 0.28156632, 0.76617895, 0.70633949])

In [ ]:
arr = np.random.rand(25)
arr

array([0.94284985, 0.80532959, 0.64441021, 0.04487778, 0.36097378,
       0.02701235, 0.03636432, 0.73228108, 0.52643563, 0.454799  ,
       0.01799456, 0.01219595, 0.46542458, 0.10964219, 0.71918603,
       0.06804372, 0.99780273, 0.99093966, 0.62490182, 0.44336635,
       0.68147719, 0.10168042, 0.21121752, 0.42677526, 0.37781778])

In [ ]:
arr = np.random.rand(5,5)
arr

array([[0.57995293, 0.14986554, 0.64812152, 0.91287476, 0.28743806],
       [0.54206244, 0.83159652, 0.72238555, 0.93705473, 0.10816679],
       [0.09935219, 0.77382807, 0.17770653, 0.53461098, 0.07708247],
       [0.21112966, 0.30395788, 0.92714286, 0.6028492 , 0.25338386],
       [0.98854793, 0.96390627, 0.86997828, 0.20609712, 0.38514572]])

## 2. randint()

In [ ]:
randint() >> return int value , need to give start & end range 

syntax:
    
np.random.randint(start,stop, size = 10)    ## stop element is not included

In [ ]:
arr = np.random.randint(10,50, size = 5)
arr

array([34, 37, 37, 31, 16])

In [ ]:
arr = np.random.randint(10,50, size = 15)
arr

array([19, 30, 28, 15, 11, 22, 19, 27, 40, 11, 46, 45, 14, 26, 25])

In [ ]:
arr = np.random.randint(10,50, size = 50)
arr

array([47, 46, 19, 47, 13, 43, 25, 35, 33, 45, 27, 29, 34, 22, 11, 33, 25,
       33, 15, 39, 21, 25, 31, 29, 38, 38, 44, 41, 16, 27, 40, 44, 26, 33,
       26, 35, 11, 23, 40, 24, 12, 11, 19, 30, 43, 10, 17, 32, 49, 17])

In [ ]:
arr = np.random.randint(10,50, size = (5,5))
arr

array([[48, 16, 42, 13, 15],
       [33, 30, 31, 49, 47],
       [43, 13, 46, 36, 19],
       [19, 21, 44, 45, 26],
       [29, 15, 29, 40, 49]])

In [ ]:
arr = np.random.randint(10,15, size =20 )
arr

array([13, 12, 10, 11, 10, 14, 12, 11, 14, 14, 12, 12, 11, 11, 13, 12, 11,
       13, 10, 13])

In [ ]:
arr = np.random.randint(10,15, size =(3,5) )
arr

array([[13, 13, 10, 12, 14],
       [10, 14, 14, 11, 12],
       [14, 13, 14, 14, 14]])

## randn()

In [ ]:
randn() >> return normally distribution value >> 

Bell shape curve >>

syntax :
    
np.random.randn(nos) ### 

In [ ]:
arr = np.random.randn(10)
arr

array([ 0.62442479,  1.05163167,  1.28386292, -0.37067398, -1.97321299,
        0.63603429, -0.80959727,  1.41543858,  0.69942029, -0.18691513])

In [ ]:
arr = np.random.randn(30)
arr

array([-2.06229193,  0.90999597, -2.33818222,  0.40625678,  0.72075484,
       -0.01337032,  1.33585741, -0.54701744, -0.98433499, -0.03738068,
        3.10239296,  1.42398433,  3.42477441, -1.26603137,  0.13531021,
        0.60723582, -0.35522164,  0.28920418, -0.73929968,  0.92118099,
       -1.14785113,  2.54277479,  1.20771886, -0.06598217, -1.48339098,
       -0.79012595, -0.48909345,  0.93886099, -0.38004161, -0.85058233])

In [ ]:
arr = np.random.randn(50)
arr

array([ 1.75500435,  0.05185369,  0.77272486, -0.27656933, -0.87677187,
        0.63960222, -0.42038716,  1.86078852,  0.59157732,  1.86085649,
       -0.35092723, -1.70347955,  2.14485693, -0.04011835,  0.25797551,
        1.20228647, -2.68367677,  0.84780876,  1.02133694,  0.04138951,
       -0.34608655, -0.07602891,  0.54875735, -0.4261092 ,  1.73801854,
        0.41777395, -1.48022949, -1.36680446,  0.37191032,  0.47184238,
        1.08760256, -0.63113638,  1.09176251,  0.16162718,  1.17040698,
        0.26760458, -0.51976801, -0.73794034,  1.05889515, -0.41337771,
       -0.78022568, -0.00414113, -0.11956736,  0.6332668 ,  0.36271357,
       -1.16058918,  0.53462219, -0.30266304, -0.0635489 ,  0.36964605])

In [ ]:
arr = np.random.ranf(50)
arr

array([0.66138982, 0.56395681, 0.52336364, 0.60023758, 0.21796502,
       0.0090768 , 0.52640822, 0.76769234, 0.88668886, 0.23822497,
       0.5713946 , 0.36282574, 0.36807703, 0.76343102, 0.44778809,
       0.83161952, 0.95002293, 0.54224464, 0.65715225, 0.83629438,
       0.32253504, 0.14270579, 0.07517808, 0.37284016, 0.28641699,
       0.25595568, 0.21067852, 0.76809681, 0.55288112, 0.62598215,
       0.9692296 , 0.3633796 , 0.00954137, 0.76378869, 0.22128633,
       0.90594228, 0.59140783, 0.30627184, 0.29715624, 0.67302757,
       0.01540222, 0.4322594 , 0.22946036, 0.02062511, 0.14431072,
       0.98708186, 0.69673326, 0.13567647, 0.65534445, 0.59868662])

## sort()

In [ ]:
np.sort() >> sort the array elements 

In [ ]:
arr = np.random.randint(10,20, size = 10)
arr

array([16, 11, 15, 10, 14, 16, 19, 10, 19, 11])

In [ ]:
arr = np.random.randint(10,20, size = 10)
print(f"{arr=}")
sort_array = np.sort(arr)
sort_array

# arr=array([18, 18, 19, 17, 14, 18, 15, 18, 19, 18])
# array([14, 15, 17, 18, 18, 18, 18, 18, 19, 19])

arr=array([18, 14, 16, 10, 13, 16, 17, 10, 19, 13])


array([10, 10, 13, 13, 14, 16, 16, 17, 18, 19])

In [ ]:
arr = np.array([[7,5],[6,1]])
sort_array = np.sort(arr)
sort_array

array([[5, 7],
       [1, 6]])

## append

In [ ]:
append() >> return array with a new values 

syntax:
var = np.append(arr1,value(arr2),axis = None)

In [ ]:
arr = np.array([4,5,6,7,8])
arr1 = np.array([14,15,16,17,18])

new_arr = np.append(arr,100)

print(f"{new_arr=}")

new_arr=array([  4,   5,   6,   7,   8, 100])


In [ ]:
arr = np.array([4,5,6,7,8])
arr1 = np.array([14,15,16,17,18])

new_arr = np.append(arr,arr1)

print(f"{new_arr=}")

new_arr=array([ 4,  5,  6,  7,  8, 14, 15, 16, 17, 18])


In [ ]:
arr = np.array([4,5,6,7,8])
arr1 = np.array([14,15,16,17,18])

new_arr = np.append(arr1,arr)

print(f"{new_arr=}")

new_arr=array([14, 15, 16, 17, 18,  4,  5,  6,  7,  8])


In [ ]:
arr1 = np.array([[4,5,6],[7,8,9]])
print(f"Array1 = \n {arr1} ")
arr2 = np.array([[14,15,16],[17,18,19]])
print(f"Array2 = \n {arr2} ")

new_arr = np.append(arr1,arr2)

print(f"New Array = \n {new_arr}")

Array1 = 
 [[4 5 6]
 [7 8 9]] 
Array2 = 
 [[14 15 16]
 [17 18 19]] 
New Array = 
 [ 4  5  6  7  8  9 14 15 16 17 18 19]


In [ ]:
arr1 = np.array([[4,5,6],[7,8,9]])
print(f"Array1 = \n {arr1} ")
arr2 = np.array([[14,15,16],[17,18,19]])
print(f"Array2 = \n {arr2} ")

new_arr = np.append(arr1,arr2, axis= 0) ## axis = 0 >> adding rows
 
print(f"New Array = \n {new_arr}")

Array1 = 
 [[4 5 6]
 [7 8 9]] 
Array2 = 
 [[14 15 16]
 [17 18 19]] 
New Array = 
 [[ 4  5  6]
 [ 7  8  9]
 [14 15 16]
 [17 18 19]]


In [ ]:
arr1 = np.array([[4,5,6],[7,8,9]])
print(f"Array1 = \n {arr1} ")
arr2 = np.array([[14,15,16],[17,18,19]])
print(f"Array2 = \n {arr2} ")

new_arr = np.append(arr1,arr2, axis= 1) ## axis = 1 >> adding columns
 
print(f"New Array = \n {new_arr}")

Array1 = 
 [[4 5 6]
 [7 8 9]] 
Array2 = 
 [[14 15 16]
 [17 18 19]] 
New Array = 
 [[ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


###  concatenate()

In [ ]:
To add multiple arrays 

syntax:
    
np.concatenate([arr1,aar2,arr3.......arrN], axis = 0) >>> The arrays must have the same shape

In [ ]:
arr1 = np.array([[4,5,6],[7,8,9]])
print(f"Array1 = \n {arr1} ")
arr2 = np.array([[14,15,16],[17,18,19]])
print(f"Array2 = \n {arr2} ")

new_arr = np.concatenate([arr1,arr2], axis= 0) ## axis = 0 >> adding rows
 
print(f"New Array = \n {new_arr}")

Array1 = 
 [[4 5 6]
 [7 8 9]] 
Array2 = 
 [[14 15 16]
 [17 18 19]] 
New Array = 
 [[ 4  5  6]
 [ 7  8  9]
 [14 15 16]
 [17 18 19]]


In [ ]:
arr1 = np.array([[4,5,6],[7,8,9]])
print(f"Array1 = \n {arr1} ")
arr2 = np.array([[14,15,16],[17,18,19]])
print(f"Array2 = \n {arr2} ")
arr3 = np.array([[10,20,30],[50,60,70]])
print(f"Array3 = \n {arr3} ")
new_arr = np.concatenate([arr1,arr2,arr3], axis= 0) ## axis = 0 >> adding rows
 
print(f"New Array = \n {new_arr}")

Array1 = 
 [[4 5 6]
 [7 8 9]] 
Array2 = 
 [[14 15 16]
 [17 18 19]] 
Array3 = 
 [[10 20 30]
 [50 60 70]] 
New Array = 
 [[ 4  5  6]
 [ 7  8  9]
 [14 15 16]
 [17 18 19]
 [10 20 30]
 [50 60 70]]


In [ ]:
arr1 = np.array([[4,5,6],[7,8,9]])
print(f"Array1 = \n {arr1} ")
arr2 = np.array([[14,15,16],[17,18,19]])
print(f"Array2 = \n {arr2} ")
arr3 = np.array([[10,20,30],[50,60,70]])
print(f"Array3 = \n {arr3} ")
new_arr = np.concatenate([arr1,arr2,arr3], axis= 1) ## axis = 1 >> adding columns
 
print(f"New Array = \n {new_arr}")

Array1 = 
 [[4 5 6]
 [7 8 9]] 
Array2 = 
 [[14 15 16]
 [17 18 19]] 
Array3 = 
 [[10 20 30]
 [50 60 70]] 
New Array = 
 [[ 4  5  6 14 15 16 10 20 30]
 [ 7  8  9 17 18 19 50 60 70]]


In [ ]:
arr1 = np.array([[4,5,6],[7,8,9]])
print(f"Array1 = \n {arr1} ")
arr2 = np.array([[14,15,16],[17,18,19]])
print(f"Array2 = \n {arr2} ")
arr3 = np.array([[10,20,30],[50,60,70]])
print(f"Array3 = \n {arr3} ")
new_arr = np.concatenate([arr1,arr2,arr3], axis= 1,) ## axis = 1 >> adding columns
 
print(f"New Array = \n {new_arr}")

In [ ]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', '

In [ ]:
arr1 = np.array([[4,5],[7,8]])  ## 2 x 2
print(f"Array1 = \n {arr1} ")
arr2 = np.array([[14,15,16],[17,18,19]]) ## 2 x3
print(f"Array2 = \n {arr2} ")
arr3 = np.array([[10,20],[50,60]]) ## 2 x 2 
print(f"Array3 = \n {arr3} ")
new_arr = np.concatenate([arr1,arr2,arr3], axis= 0,) ## axis = 0 >> adding row
 
print(f"New Array = \n {new_arr}")

Array1 = 
 [[4 5]
 [7 8]] 
Array2 = 
 [[14 15 16]
 [17 18 19]] 
Array3 = 
 [[10 20]
 [50 60]] 


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [ ]:
arr1 = np.array([[4,5],[7,8]])  ## 2 x 2
print(f"Array1 = \n {arr1} ")
arr2 = np.array([[14,15,16],[17,18,19]]) ## 2 x3
print(f"Array2 = \n {arr2} ")
arr3 = np.array([[10,20],[50,60]]) ## 2 x 2 
print(f"Array3 = \n {arr3} ")
new_arr = np.concatenate([arr1,arr2,arr3], axis= 1,) ## axis = 1 >> adding column
 
print(f"New Array = \n {new_arr}")

Array1 = 
 [[4 5]
 [7 8]] 
Array2 = 
 [[14 15 16]
 [17 18 19]] 
Array3 = 
 [[10 20]
 [50 60]] 
New Array = 
 [[ 4  5 14 15 16 10 20]
 [ 7  8 17 18 19 50 60]]


# np.ceil

In [ ]:
3.2 >> 4
4.5 >> 5
6.8 >> 7

In [ ]:
syntax: np.ceil(value)

In [ ]:
np.ceil(6.8)

7.0

In [ ]:
np.ceil(3.2)

4.0

In [ ]:
arr = np.array([31.2,7.8,5.2])
new_arr = np.ceil(arr)
new_arr

array([32.,  8.,  6.])

In [ ]:
## np.floor() 

syntax >> np.floor(value)

In [ ]:
arr = np.array([31.2,7.8,5.2])
new_arr = np.floor(arr)
new_arr

array([31.,  7.,  5.])

In [ ]:
np.floor(3.14)

3.0

### np.around()

In [ ]:
round(13.98708186)

14

In [ ]:
np.round(13.98708186)

14.0

In [ ]:
arr = np.linspace(1,10, num = 100)
print(arr)
arr_round = np.around(arr)
arr_round

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

array([ 1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  6.,  6.,
        6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  7.,  7.,  7.,  7.,
        7.,  7.,  7.,  7.,  7.,  7.,  7.,  8.,  8.,  8.,  8.,  8.,  8.,
        8.,  8.,  8.,  8.,  8.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,
        9.,  9.,  9., 10., 10., 10., 10., 10., 10.])

## np.where()

In [ ]:
np.where(condition) >> return index value of an array element 

>>> return value in tuple


In [ ]:
list1 = [3,4,5,6,7,8,9]

index_list = list1.index(5)
index_list

2

In [4]:
list1 = [3,4,5,6,7,8,9,5,2,7,5,4,10,5]

index_list = list1.index(5)
index_list

2

In [ ]:
index_list=[]
for index,value in enumerate(list1):
    if value == 5:
        index_list.append(index)
    
print(index_list)

[2, 7, 10, 13]


In [ ]:
index_list=[index for index , value in enumerate(list1) if value == 5]



# for index,value in enumerate(list1):
#     if value == 5:
#         index_list.append(index)
    
print(index_list)

[2, 7, 10, 13]


In [5]:
import numpy as np
arr = np.array(list1)
print(arr)

index = np.where(arr==5)
print(index)



[ 3  4  5  6  7  8  9  5  2  7  5  4 10  5]
(array([ 2,  7, 10, 13]),)


In [ ]:
arr = np.array(list1)
print(arr)

index = np.where(arr==5)

var_list = list(index)
var_list



[ 3  4  5  6  7  8  9  5  2  7  5  4 10  5]


[array([ 2,  7, 10, 13], dtype=int64)]

In [ ]:
arr = np.array(list1)
print(arr)

index = np.where(arr == 2)

index



[ 3  4  5  6  7  8  9  5  2  7  5  4 10  5]


(array([8], dtype=int64),)

In [ ]:
arr = np.array(list1)
print(arr)

index = np.where(arr >= 5)

index



[ 3  4  5  6  7  8  9  5  2  7  5  4 10  5]


(array([ 2,  3,  4,  5,  6,  7,  9, 10, 12, 13], dtype=int64),)

In [ ]:
arr = np.array(list1)
print(arr)

index = np.where(arr!= 5)

index



[ 3  4  5  6  7  8  9  5  2  7  5  4 10  5]


(array([ 0,  1,  3,  4,  5,  6,  8,  9, 11, 12], dtype=int64),)

### convert array to list

In [ ]:
arr = np.array(list1)
print(arr)

index = np.where(arr >= 5)

index_list = list(index)
index_list



[ 3  4  5  6  7  8  9  5  2  7  5  4 10  5]


[array([ 2,  3,  4,  5,  6,  7,  9, 10, 12, 13], dtype=int64)]

In [18]:
a=np.array([1,2,3,45.5,3])
list(a)

[1.0, 2.0, 3.0, 45.5, 3.0]

In [ ]:
arr = np.array(list1)
print(arr)

index = np.where(arr >= 5)

index_list = index[0]
index_list



[ 3  4  5  6  7  8  9  5  2  7  5  4 10  5]


array([ 2,  3,  4,  5,  6,  7,  9, 10, 12, 13], dtype=int64)

In [ ]:
arr = np.array(list1)
print(arr)

index = np.where(arr >= 5)

index_list = index
index_list



[ 3  4  5  6  7  8  9  5  2  7  5  4 10  5]


(array([ 2,  3,  4,  5,  6,  7,  9, 10, 12, 13], dtype=int64),)

In [6]:
arr = np.array(list1)
print(arr)

index = np.where(arr >= 5)

index_list = index[0].tolist()
print(index_list)



[ 3  4  5  6  7  8  9  5  2  7  5  4 10  5]
[2, 3, 4, 5, 6, 7, 9, 10, 12, 13]


In [ ]:
arr = np.array(list1)
print(arr)

index_list = np.where(arr >= 5)[0].tolist()

print(index_list)



[ 3  4  5  6  7  8  9  5  2  7  5  4 10  5]
[2, 3, 4, 5, 6, 7, 9, 10, 12, 13]


In [ ]:
arr = np.array([[2, 3, 4], [5, 6, 7],[ 9, 10, 12],[ 13,14,15]])
print(arr)
result = np.where(arr == 10)
result

[[ 2  3  4]
 [ 5  6  7]
 [ 9 10 12]
 [13 14 15]]


(array([2], dtype=int64), array([1], dtype=int64))

In [ ]:
arr = np.array([[2, 3, 4], [5, 6, 7],[ 9, 10, 12],[ 13,14,15]])
print(arr)
result = np.where(arr%2==0)
result

[[ 2  3  4]
 [ 5  6  7]
 [ 9 10 12]
 [13 14 15]]


(array([0, 0, 1, 2, 2, 3], dtype=int64),
 array([0, 2, 1, 1, 2, 1], dtype=int64))

In [2]:
import numpy as np
arr = np.array([[2, 3, 4], [5, 6, 7],[ 9, 10, 12],[ 13,14,15]])
print(arr)
result = np.where(arr%2==0)
print(result)
row_index = result[0].tolist()
columns_index = result[1].tolist()

print(row_index)
print(columns_index)

[[ 2  3  4]
 [ 5  6  7]
 [ 9 10 12]
 [13 14 15]]
(array([0, 0, 1, 2, 2, 3], dtype=int64), array([0, 2, 1, 1, 2, 1], dtype=int64))
[0, 0, 1, 2, 2, 3]
[0, 2, 1, 1, 2, 1]


## Numerical Operations 

In [ ]:
# add 10 in every element 
arr = np.array([2, 3, 4, 5, 6, 7, 9, 10, 12, 13,14,15])

new_arr = arr+10
new_arr

array([12, 13, 14, 15, 16, 17, 19, 20, 22, 23, 24, 25])

In [ ]:
# substract 5 in every element 
arr = np.array([2, 3, 4, 5, 6, 7, 9, 10, 12, 13,14,15])

new_arr = arr-5
new_arr

array([-3, -2, -1,  0,  1,  2,  4,  5,  7,  8,  9, 10])

In [ ]:
# substract 5 in every element 
arr = np.array([2, 3, 4, 5, 6, 7, 9, 10, 12, 13,14,15])

new_arr = arr**2
new_arr

array([  4,   9,  16,  25,  36,  49,  81, 100, 144, 169, 196, 225])

## Matrix Addition

In [25]:
arr1 = np.array([[2, 3, 4], [5, 6, 7]])
print(f"Array1 = \n{arr1}")
arr2 = np.array([[ 9, 10, 12],[ 13,14,15]])
print(f"Array2 = \n{arr2}")

Array1 = 
[[2 3 4]
 [5 6 7]]
Array2 = 
[[ 9 10 12]
 [13 14 15]]


In [26]:
add = arr1 + arr2
add

array([[11, 13, 16],
       [18, 20, 22]])

## np.add()

In [28]:
arr3 = np.array([[ 9, 10, 12],[ 13,14,15]])
new_arr = np.add(arr3,arr2,arr1)
new_arr

array([[18, 20, 24],
       [26, 28, 30]])

## Matrix Multiplication 

In [ ]:
arr1 = np.array([[2, 3, 4], [5, 6, 7]])
print(f"Array1 = \n{arr1}")
arr2 = np.array([[ 9, 10, 12],[ 13,14,15]])
print(f"Array2 = \n{arr2}")

arr = arr1 * arr2
print('*'*30)
arr = np.multiply(arr1,arr2)
print(arr)

Array1 = 
[[2 3 4]
 [5 6 7]]
Array2 = 
[[ 9 10 12]
 [13 14 15]]
******************************
[[ 18  30  48]
 [ 65  84 105]]


## Matrxi Dot Product

In [ ]:
arr1 = np.array([[2, 3, 4], [5, 6, 7],[2,3,4]])
print(f"Array1 = \n{arr1}")
arr2 = np.array([[ 9, 10, 12],[ 13,14,15],[5,6,7]])
print(f"Array2 = \n{arr2}")

# arr = arr1 * arr2
print('*'*30)
arr = np.dot(arr1,arr2)
print(arr)

Array1 = 
[[2 3 4]
 [5 6 7]
 [2 3 4]]
Array2 = 
[[ 9 10 12]
 [13 14 15]
 [ 5  6  7]]
******************************
[[ 77  86  97]
 [158 176 199]
 [ 77  86  97]]


In [ ]:
## arr1 = np.array([[2, 3],[ 4,5]])
print(f"Array1 = \n{arr1}")
arr2 = np.array([[6,7 ],[ 4,5]])
print(f"Array2 = \n{arr2}")

# arr = arr1 * arr2
print('*'*30)
arr = np.dot(arr1,arr2)
print(arr)

Array1 = 
[[2 3]
 [4 5]]
Array2 = 
[[6 7]
 [4 5]]
******************************
[[24 29]
 [44 53]]


In [ ]:
2*6 + 3*4

24

In [ ]:
4 *6 + 5 *4

44